apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 4317
          name: grpc
        - containerPort: 4318
          name: http
        args:
        - --config=/etc/otel/otel-config.yaml
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/otel
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: otel-config 