apiVersion: v1
kind: Service
metadata:
  name: envoy-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 1989
      protocol: TCP
      name: http
    - port: {{ .Values.service.adminPort }}
      targetPort: 9901
      protocol: TCP
      name: admin
  selector:
    app: envoy