global:
  namespace: "elchi-stack"
  clusterDomain: "cluster.local"
  mainAddress: "backend.elchi.io" # Required
  port: ""  # If empty, will use 80 for HTTP or 443 for HTTPS based on tlsEnabled
  tlsEnabled: true
  timezone: ""  # If empty, will use host timezone. Examples: "Europe/Istanbul", "UTC", "America/New_York"
  versions:
    - tag: v0.1.0-v0.13.4-envoy1.33.5
    - tag: v0.1.0-v0.13.4-envoy1.34.2
  installMongo: false
  installVictoriaMetrics: true
  internalCommunication: false
  mongodb:
    hosts: "162.217.249.158"
    username: "elchi"
    password: "sr3f*-210=12fgvSE0!eeC3"
    database: "elchi"
    scheme: "mongodb"
    port: "27017"
    replicaset: ""
    timeoutMs: "5000"
    tlsEnabled: "false"
    authSource: "admin"
    authMechanism: "SCRAM-SHA-1"
  victoriametrics:
    endpoint: "" # Required when installVictoriaMetrics is false (e.g., "http://external-vm.example.com:8428")
  elchiBackend:
    controlPlaneDefaultReplicas: 2
    controllerDefaultReplicas: 2
